name: Build and Push Nginx Image

on:
  workflow_dispatch:  # Manually triggered

jobs:
  build-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Nginx image
        uses: docker/build-push-action@v2
        with:
          context: ../../infra/ngnix
          push: true
          tags: |
            335160831887.dkr.ecr.ap-south-1.amazonaws.com/aliensgroup/nginx:latest
